### ISSUE TITLE
Problema cadastro novo paciente

### ISSUE THREAD

**Issue by Yoac-eng** [ciroDourado/api-vacinas#32]
Ao cadastrar um novo paciente, é possível que o paciente seja cadastrado mas seu endereço não.
Alterar isso de forma que um novo paciente só seja cadastrado caso seu endereço seja válido.

**Comment by ciroDourado** [comment]
O erro foi tratado com sucesso. O cadastro do paciente somente irá encadear o cadastro de endereço caso todos os campos estejam corretos, e caso o paciente ainda não exista.
