### ISSUE TITLE
Alterar resposta de requisição

### ISSUE THREAD

**Issue by Yoac-eng** [ciroDourado/api-vacinas#34]
Ao receber uma requisição com os campos vazios ou com dados que não sejam compatíveis, a resposta continua sendo OK desde que os dados sejam dos campos esperados.
Discutir possível alteração dessa resposta.

**Comment by ciroDourado** [comment]
O erro foi devidamente tratado com o módulo de Requests em conjunto com o módulo de Respostas (ambos na pasta Helpers). Todos os casos estão cobertos. A semântica do OK é basicamente para indicar que a comunicação com o servidor foi bem-sucedida. Mensagens mais específicas estarão encapsuladas dentro.

Deixo em aberto a discussão para mudar a resposta HTTP.
